<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE help [
<!ENTITY lt "#38;#60;">
<!ENTITY gt "&#62;">
<!ENTITY amp "&#38;#38;">
<!ELEMENT help (name , synopsis , description , arguments+ , outputs* , example* , bugs* , reporting* , see-also*)*>
<!ELEMENT name (#PCDATA)>
<!ELEMENT synopsis (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT arguments (positional* , required-flagged* , optional-flagged*)*>
<!ELEMENT positional (intro* , argument* , explanation*)*>
<!ELEMENT required-flagged (intro* , argument* , explanation*)*>
<!ELEMENT optional-flagged (intro* , argument* , explanation*)*>
<!ELEMENT intro (#PCDATA)>
<!ELEMENT argument (#PCDATA)>
<!ELEMENT explanation (#PCDATA)>
<!ELEMENT outputs (output* , explanation*)*>
<!ELEMENT output (#PCDATA)>
<!ELEMENT example (#PCDATA)>
<!ELEMENT bugs (#PCDATA)>
<!ELEMENT reporting (#PCDATA)>
<!ELEMENT see-also (#PCDATA)>
]>

<help>
	<name>mris_curvature</name>
	<synopsis>mris_curvature [&lt;options&gt;] insurf</synopsis>
	<description>This program will compute the second fundamental form of a cortical surface. It will create two new files &lt;hemi&gt;.&lt;surface&gt;.H and &lt;hemi&gt;.&lt;surface&gt;.K with the mean and Gaussian curvature respectively. When neighrhood size is asked for below, typical value is 2.</description>
  <arguments>
    <positional>
      <argument>&lt;insurf&gt;</argument>
      <explanation>input surface file</explanation>
    </positional>
    <required-flagged>
      <intro>None.</intro>
    </required-flagged>
    <optional-flagged>
      <argument>-w</argument>
      <explanation>save curvature files (will only generate screen output without this option)</explanation>
      <argument>-max</argument>
      <explanation>save  1st (max) principal curvature in ?h.&lt;surface&gt;.max file</explanation>
      <argument>-mgh</argument>
      <explanation>save outputs in .mgz format</explanation>
      <argument>-min</argument>
      <explanation>save  2nd (min) principal curvature in ?h.&lt;surface&gt;.min file</explanation>
      <argument>-a &lt;avgs&gt;</argument>
      <explanation>perform &lt;avgs&gt; iterative averages of curvature measure before saving</explanation>
      <argument>-nbrs &lt;nbrs&gt;</argument>
      <explanation>set neighborhood size to nbrs </explanation>
      <argument>-seed N</argument>
      <explanation>set random number generator to seed N</explanation>
      <argument>-curvs surf nbrhdsize stem</argument>
      <explanation>Stand-alone option to save H (mean), K (gaussian), k1, and k2 curvatures to stem.{curvname}.mgz</explanation>
      <argument>-H surf nbrhdsize stem</argument>
      <explanation>Stand-alone option to save H mean curvature to stem.H.mgz</explanation>
      <argument>-K surf nbrhdsize stem</argument>
      <explanation>Stand-alone option to save K gaussian curvature to stem.K.mgz</explanation>
      <argument>-k1 surf nbrhdsize stem</argument>
      <explanation>Stand-alone option to save k1 (primary principle) curvature to stem.k1.mgz. nbrhdsize typically is 2.</explanation>
      <argument>-k2 surf nbrhdsize stem</argument>
      <explanation>Stand-alone option to save k2 (secondary principle) curvature to stem.k2.mgz. nbrhdsize typically is 2. </explanation>
      <argument>-k1k2 surf nbrhdsize stem</argument>
      <explanation>Stand-alone option to save k1 and k2 curvature to stem.{k1,k2}.mgz </explanation>
    </optional-flagged>
  </arguments>
  <outputs>
    <output>insurf.h</output>
    <explanation>mean curvature file</explanation>
    <output>insurf.K</output>
    <explanation>gaussian curvature file</explanation>
  </outputs>
	<example>mris_curvature lh.pial
Compute the curvature and do not produce output files. </example>
	<example>mris_curvature -w -a 10 lh.pial
Smooth 10 iterations and produce output files.</example>
  <reporting>Report bugs to &lt;freesurfer@nmr.mgh.harvard.edu&gt;</reporting>
</help>

